// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flowdocument.proto

package org.opennms.netmgt.flows.persistence.model;

/**
 * Protobuf enum {@code Locality}
 */
public enum Locality
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PUBLIC = 0;</code>
   */
  PUBLIC(0),
  /**
   * <code>PRIVATE = 1;</code>
   */
  PRIVATE(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>PUBLIC = 0;</code>
   */
  public static final int PUBLIC_VALUE = 0;
  /**
   * <code>PRIVATE = 1;</code>
   */
  public static final int PRIVATE_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Locality valueOf(int value) {
    return forNumber(value);
  }

  public static Locality forNumber(int value) {
    switch (value) {
      case 0: return PUBLIC;
      case 1: return PRIVATE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Locality>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Locality> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Locality>() {
          public Locality findValueByNumber(int number) {
            return Locality.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.opennms.netmgt.flows.persistence.model.EnrichedFlowProtos.getDescriptor().getEnumTypes().get(3);
  }

  private static final Locality[] VALUES = values();

  public static Locality valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Locality(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Locality)
}

