[[nephron-persistence]]
= Persistence

Nephron aggregates flows over time and by several aspects (for example, exporters, interfaces, dscps (differentiated service code points), applications, hosts, and conversations).

"Application" and "conversation" are flow classifications.
OpenNMS classifies flows into applications based on rules that consider the protocol, src/dst address, and src/dst port of flows.
OpenNMS classifies flows into the same conversation if they have matching hosts, applications, protocols, and (exporter) locations.
(The src/dst host distinction is not important for conversation classification.)

Nephron can output flow summary aggregations to different systems:

* <<flows-elastic,Elasticsearch>>
* <<flows-cortex,Cortex>>
* <<flows-kafka,Kafka>>

[[flows-elastic]]
== Elasticsearch persistence

Use the following command-line argument to configure Elasticsearch persistence:

[source, console]
----
--elasticUrl=http://<server>:9200
----

For additional options, see link:https://github.com/OpenNMS/nephron/blob/master/main/src/main/java/org/opennms/nephron/NephronOptions.java[NephronOptions].

If no Elasticsearch output is required, then set `--elasticUrl` as empty.

[[flows-cortex]]
== Cortex persistence

Use the following command-line argument to configure Cortex persistence:

[source, console]
----
--cortexWriteUrl=http://<server>:9009/api/v1/push
----

Stores the following metrics:


[options="header" cols="2,1,2"]
|===

| Metric
| Complete/TopK
| Labels

| EXPORTER_INTERFACE
| complete
| pane, direction, nodeId, ifIndex

| EXPORTER_INTERFACE_TOS
| complete
| pane, direction, nodeId, ifIndex, dscp

| BY_APP_${nodeId}_${ifIndex}
| topK
| pane, direction, application

| BY_HOST_${nodeId}_${ifIndex}
| topK
| pane, direction, host

| BY_TOS_AND_APP_${nodeId}_${ifIndex}
| topK
| pane, direction, dscp, application

| BY_TOS_AND_HOST_${nodeId}_${ifIndex}
| topK
| pane, direction, dscp, host
|===

The nodeId and ifIndex are encoded in metric names for some of the aggregations to reduce the product of label cardinalities.

Labels:

[options="header" cols="1,2"]
|===
| Name
| Description/Note

| pane
| Additional label to distinguish samples for the same timestamp.
Used for early/late results and Cortex's time-ordering constraint.

| direction
| Possible values: `in` and `out`

| nodeId
| The node ID of the flow exporter

| ifIndex
| Interface index

| dscp
| Differentiated service code points; possible values: 0–63.

| host, host2
| IP addresses in dot notation

| application
| The result of classifying flows into applications.

| protocol
| Protocol number; possible values: integer range

| location
| TODO: from exporter node meta data?
|===

For additional options, see link:https://github.com/OpenNMS/nephron/blob/master/main/src/main/java/org/opennms/nephron/CortexOptions.java[CortexOptions].

[[flows-kafka]]
== Kafka persistence

Use the following command-line argument to configure Kafka persistence:

[source, console]
----
--flowDestTopc=...
----
