// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flowdocument.proto

package org.opennms.netmgt.flows.persistence.model;

public interface NodeInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NodeInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string foreign_source = 1;</code>
   */
  java.lang.String getForeignSource();
  /**
   * <code>string foreign_source = 1;</code>
   */
  com.google.protobuf.ByteString
      getForeignSourceBytes();

  /**
   * <code>string foregin_id = 2;</code>
   */
  java.lang.String getForeginId();
  /**
   * <code>string foregin_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getForeginIdBytes();

  /**
   * <code>uint32 node_id = 3;</code>
   */
  int getNodeId();

  /**
   * <code>repeated string categories = 4;</code>
   */
  java.util.List<java.lang.String>
      getCategoriesList();
  /**
   * <code>repeated string categories = 4;</code>
   */
  int getCategoriesCount();
  /**
   * <code>repeated string categories = 4;</code>
   */
  java.lang.String getCategories(int index);
  /**
   * <code>repeated string categories = 4;</code>
   */
  com.google.protobuf.ByteString
      getCategoriesBytes(int index);
}
