{
 "title": "Project Nephron",
 "description": "Comparision of flow traffic derived from raw vs aggregated metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Traffic derived from sFlow (raw)",
   "type": "graph",
   "description": "eth0(2) on ny-nms-1 (hsflowd)",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "functions": [
      { "name": "topN", "parameters": [ "0" ] },
      {
       "name": "includeOther",
       "parameters": []
      },
      { "name": "withExporterNode", "parameters": [ "1" ] },
      { "name": "withIfIndex", "parameters": [ "2" ] },
      {
       "name": "onlyIngress",
       "parameters": []
      }
     ],
     "metric": "applications"
    }
   ]
  },
  {
   "title": "Top 5 Applications - Raw",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "functions": [
      {
       "name": "asTableSummary",
       "parameters": []
      },
      { "name": "topN", "parameters": [ "5" ] }
     ],
     "metric": "applications"
    }
   ]
  },
  {
   "title": "Traffic derived from sFlow (aggregated)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Ingress",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "bytes_ingress",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "grouped_by:EXPORTER_INTERFACE AND context:TOTAL AND exporter.foreign_id:ny-nms-1 AND if_index:2",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top 5 Applications - Aggregated",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "application",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "4", "size": "5" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "bytes_ingress",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "bytes_egress",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "grouped_by:EXPORTER_INTERFACE_APPLICATION AND context:TOPK AND exporter.foreign_id:ny-nms-1 AND if_index:2",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Raw Flows",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "netflow.direction:ingress AND node_exporter.foreign_id:ny-nms-1 AND netflow.input_snmp:2",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Aggregated Flows",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "grouped_by:EXPORTER_INTERFACE AND context:TOTAL AND exporter.foreign_id:ny-nms-1 AND if_index:2",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}